#pragma once

#define PLAYER_OBJECT_BASE					*(DWORD*)(0x7666A78)

#define pResolution							*(DWORD*)(0x5750320)
#define pFontSize							*(DWORD*)(0x773D130)
#define pScreenDivisorX 					*(float*)(0x574FE90)
#define pScreenDivisorY 					*(float*)(0x574FE94)
#define pScreenWidth						*(DWORD*)(0x6C4158)
#define pScreenHeight 						*(DWORD*)(0x6C415C)
#define pScreenWidthBase 					640
#define pScreenHeightBase					480
#define pClipPrecisionX						*(float*)(0x6A967C)
#define pClipPrecisionY		 				*(float*)(0x5E9D4E)

#define pWndProc							(WNDPROC)(0x4A9BD0)
#define pProtocolCore						((int(*)(DWORD, LPBYTE, int, int))(0x4DB720))
#define pDrawDamage							((void(*)(int, int, int, int, char))(0x53DA80))
#define pUnkFormatPoint						((void(*)(int, float, float, float, float, float, float, float, float, char, int))(0x60DCF0))
#define pDrawMonsterHP						((void(*)())(0x598350))
#define pGetPositionFromAngle				((void(*)(LPVOID, int*, int*))(0x60C740))

#define pSetBlend							((void(__cdecl*)(BYTE)) 0x60CB90)
#define pEnableAlpha						((void(*)(char))(0x60CB90))
#define pDisableAlpha						((void(*)())(0x60CC20))
#define pDisableAlphaBlend					((void(*)())(0x60CB10))
#define pDrawForm							((void(*)(float, float, float, float))(0x60DC30))
#define pDrawText							((int(*)(int, int, LPCSTR, int, char, int))(0x5486E0))
#define pDrawUserInfo						((void(*)(int, int, float, float, int, int, float, int))(0x5484B0))
#define pDrawImage							((void(*)(int, float, float, float, float, float, float, float, float, char, float))(0x60DCF0))
#define pSerialPacketEncrypt()				((BYTE(__thiscall*)(void*, const char*))(0x409580))((void*)(0x57500B0), (const char*)(0x57548F3))
#define pSerialPacketDecrypt()				((BYTE(__thiscall*)(void*, const char*))(0x409340))((void*)(0x57500B0), (const char*)(0x57548F3))
#define pSimpleModulusEncrypt(a, b, c)		((int(__thiscall*)(void*, void*, void*, int))(0x674DC0))((void*)(0x5754800), a, b, c)
#define pSimpleModulusDecrypt(a, b, c)		((int(__thiscall*)(void*, void*, void*, int))(0x674E30))((void*)(0x5754848), a, b, c)
#define pSetGlow							((void(*)(int, float, DWORD, struct GlowColor*, DWORD))(0x5F6220))
#define pShowMessage						((char(*)(const char*, const char*, int))(0x549630))
#define pRenderizeMonster					((ViewportInfo*(*)(int, DWORD, int, int))(0x434E60))
#define pRenderizeModel						((ViewportInfo*(*)(int, int, DWORD, int, int))(0x509410))
#define pShowModel							((int(*)(int, int, char, int, float*, int, char))(0x5CF110))
#define pLoadModel							((void(*)(int, const char*, const char*, int))(0x5FACA0))
#define pLoadTexture						((void(*)(int, const char*, GLint, GLint, GLsizei))(0x5FA860))
#define pLoadModels							((void(*)())(0x5FD0E0))
#define pLoadTextures						((void(*)())(0x5FE910))
#define pLoadInterfaces						((void(*)())(0x6096B0))
#define pLoadJPG							((char(*)(const char*, int, int, int, int, char))(0x62C1E0))
#define pLoadTGA							((char(*)(const char*, int, int, int, int, int))(0x62C670))
#define pLoadSounds							((void(*)())(0x607CE0))
#define pConnect							((int(*)(LPCSTR, WORD))(0x4BBA20))
#define pSetEvent							((int(*)(DWORD))(0x60FB20))
#define pInterfaceDraw1						((void(*)(int))(0x598C30))
#define pPShopThis							((LPVOID(*)())(0x44C850))
#define pPShopSet(viewport)					((void(__thiscall*)(LPVOID, ViewportInfo*))(0x44BF70))(pPShopThis(), viewport)
#define pRefreshGame						((int(*)(ViewportInfo*))(0x4EA700))
#define pFixText()							((void(*)(int, int, LPCSTR))(0x5487E0))(0, 0, "")
#define pCreateSign							((LPBYTE(__thiscall*)(LPVOID, short, int, char, float, float, float, int, int, float))(0x4127F0))
#define pCreateSign2						((LPBYTE(__thiscall*)(LPVOID, short, int, int, float, float, float))(0x412C40))
#define pDestroySign						((void(*)(ViewportInfo*))(0x4127C0))
#define pGetEffectPosition					((int(__thiscall*)(DWORD, DWORD, DWORD, DWORD, char))(0x4E4610))
#define pShowEffect1						((int(*)(short, DWORD, float, float*, DWORD, DWORD, DWORD))(0x53DE20))
#define pShowEffect2						((int(*)(int, DWORD, DWORD, float*, DWORD, float, DWORD))(0x5353B0))
#define pMakePreviewCharacter				((void(*)(int, BYTE*, int, int))(0x50A590))

#define pGetAllianceName(i)					((char*)(2 * (11 * i) + 0x785B794))

#define GET_MAX_WORD_VALUE(x)				((x > 65000) ? 65000 : (WORD)(x))